FROM alpine:3.20

RUN apk add --no-cache python3 py3-pip gcc musl-dev python3-dev
RUN pip3 install --no-cache-dir fastapi uvicorn

WORKDIR /app
COPY main.py .

EXPOSE 80
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
